name: Run Daily Nifty Alert

on:
  schedule:
    - cron: '0 3 * * *'  # Runs every day at 3:00 AM UTC (8:30 AM IST)
  workflow_dispatch:     # Allow manual run from GitHub

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install yfinance

      - name: Run script
        env:
          EMAIL_SENDER: ${{ secrets.EMAIL_FROM }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASS }}
          EMAIL_RECEIVER: ${{ secrets.EMAIL_TO }}
        run: |
          python nifty_alert.p
